### ISSUE TITLE
add line to README

### ISSUE THREAD

**Issue by bdietz** [ShellyYBlack/bd-extent-calculator#1]
Add script to directory where dockerfile is before building image so that it is copied to working directory.

**Comment by ShellyYBlack** [comment]
Assuming you git cloned the whole repo, when you built the image, the
script was already in the same directory as the Dockerfile on your host,
right?

I tested building the image and running the container. The working
directory was /src where all the files, including the script, get copied
to. So I could run the script as soon as starting the container.

**Comment by bdietz** [comment]
Probably not. I think I just grabbed the Dockerfile. In this case, what about adding "clone repository or download all files" to the readme? Do you think that's implied?

**Comment by ShellyYBlack** [comment]
I'll add a `git clone` instruction. Thanks for confirming.

Shelly
